export const environment = {
    production: false,
    apiBaseUrl: "http://localhost:3000/api",
    authorizationHttpHeader: "Authorization",
    addRace: "Add Race",
    addTeam: "Add Team",
    bearerPrefix: "BEARER ",
    backToRace: "Back to race",
    backToRaceList: "Back to race list",
    backToTeamList: "Back to team list",
    circuitName: "Circuit name",
    count: "count",
    delete: "Delete",
    edit: "Edit",
    editTeam: "Edit Team",
    editRace: "Edit Race",
    footerText: "Maharishi International University. All Rights Reserved.",
    hi: "Hi",
    homeRoute: "",
    home: "Home",
    listOfMotoGpRaces: "List of MotoGP Races",
    login: "Login",
    loginUnsuccess: "Login unsuccessful",
    loginRoute: "login",
    logout: "Logout",
    name: "Name",
    next: "Next",
    noOfTeams: "No. of Teams",
    offset: "offset",
    password: "Password",
    passwordRepeat: "Password Repeat",
    pageNotFoundRoute: "**",
    profileROute: "profile",
    profile: "Profile",
    previous: "Previous",
    postMethod: "post",
    putMethod: "put",
    races: "Races",
    racesApiBaseUrl: "http://localhost:3000/api/races",
    raceIdParam: "raceId",
    racesRoute: "races",
    racesRouteRelative: "/races",
    racesAddRoute: "races/add",
    racesRaceEditRoute: "races/:raceId/edit",
    raceDetailRoute: "races/:raceId",
    raceTeamListRoute: "races/:raceId/teams",
    raceTeamAddRoute: "races/:raceId/teams/add",
    raceTeamEditRoute: "races/:raceId/teams/:teamId/edit",
    registerRoute: "register",
    register: "Register",
    riderName: "Rider name",
    rank: "Rank",
    save: "Save",
    season: "Season",
    teams: "teams",
    teamName: "Team name",
    tokenNotFound: "Token not found",
    tokenLocalStorageItem: "token",
    teamDetailRoute: "races/:raceId/teams/:teamId",
    teamsRoute: "teams",
    teamIdParam: "teamId",
    username: "Username",
    userRegistered: "User Registered",
    userRegistrationFailed: "User Registration Failed",
    usersApiBaseUrl: "http://localhost:3000/api/users",
    viewTeams: "View Teams",
    welcomeMsg: "Welcome to MEAN MotoGP Races",
    winner: "Winner"
};
